app:
  heartbeat_interval: 5 # the interval time for heartbeat jobs(unit: second)
  collect_interval: 30 # the interval time for collect jobs(unit: second)
  gateway_addr: "192.168.0.4:15001" # the gateway address
  base_dir: "e:\\collector" # base directory for program files

tls:
  switch: false # the switch for the ca certification(default closed)
  perm: "cert/client.pem" # the perm file for ca certification in grpc client
  key: "cert/client.key" # the key file for ca certification in grpc client
  ca: "cert/ca.pem" # the ca file for ca certification in grpc client

log:
  output_level: "info" # the log level with value in [debug, info, warn, error]
  output_path: "stdout" # a file system path to write the log data to
  rotation_path: "./logs/TL-Data-Collector.log" # the path to a rotating log file
  rotation_max_size: 100 # the maximum size in megabytes of a log file before it get rotated. It defaults to 100 megabytes.
  rotation_max_age: 30 # the maximum number of days to retain old log files based on the timestamp encoded in their filename
  rotation_max_backups: 1000 # the maximum number of old log files to retain
  json_encoding: false # whether the log is formatted as JSON

